// Generated by CoffeeScript 1.3.3
(function() {
  var onMouseUp, onResize;

  onResize = function(event) {
    return console.log("log coffeescript event");
  };

  onResize();

  $(document).ready(function() {
    var _this = this;
    $('#gridContainer').bind('mouseenter', function(event) {
      return console.log("mouse enter event");
    });
    $('#gridContainer').bind('click', function(event) {
      console.log("mouse enter event");
      return console.log(event);
    });
    return $(document).mousedown(function(event, x) {
      console.log("mousedown");
      console.log(event);
      return console.log(x);
    });
  });

  onMouseUp = function(event) {
    return alert(event);
  };

}).call(this);
