// Generated by CoffeeScript 1.3.3
(function() {
  var createGrid, layout, onResize, registerMouseOvers, registerSelectBox;

  $(document).ready(function() {
    var layout;
    createGrid();
    registerMouseOvers();
    registerSelectBox();
    layout = 'full';
    onResize();
    return $(window).resize(function() {
      return onResize();
    });
  });

  layout = 'full';

  onResize = function() {
    var title, wrapper;
    title = $('#titlecontainer');
    wrapper = $('#wrapper');
    console.log(wrapper.height());
    if (wrapper.height() > 700) {
      console.log("is high");
      if (layout === 'full') {
        $(title).animate({
          marginTop: 0,
          marginLeft: 0,
          marginRight: 0
        });
        console.log("switched to compact mode");
        return layout = 'compact';
      }
    } else {
      if (layout === 'compact') {
        $(title).animate({
          marginTop: 75,
          marginRight: 75,
          marginLeft: 75
        });
        console.log("switched to full mode");
        return layout = 'full';
      }
    }
  };

  createGrid = function() {
    var gridContainer;
    return gridContainer = $('#gridContainer');
  };

  registerMouseOvers = function() {
    var elCategories, gridItems, myItem, overlay, overlayImage, overlaysrc, src, _i, _len, _results;
    gridItems = $('#gridContainer > *');
    _results = [];
    for (i = 0, _len = gridItems.length; i < _len; i++) {
      myItem = gridItems[i];
      overlay = document.createElement('div');
      overlay.setAttribute('class', 'overlay');
      src = myItem.children[0].getAttribute('src').split('.');
      overlaysrc = src[0] + '_pt.' + src[1];
      overlayImage = document.createElement('img');
      overlayImage.setAttribute('src', overlaysrc);
      $(overlay).append(overlayImage);
      $(myItem).append(overlay);
      $(overlay).mouseover(function() {
        return $(this).animate({
          opacity: 0.0
        }, 100);
      });
      $(overlay).mouseleave(function() {
        return $(this).animate({
          opacity: 1
        }, 500);
      });
      elCategories = $(myItem).attr("data-categories");
      if (elCategories.split(' ')[0] === "product") {
        _results.push($(myItem).css("border", "red 5px solid"));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  registerSelectBox = function() {
    var gridItems;
    $('#selectmenu').change(function(event) {
      return console.log('selectmenu changed into ' + event.currentTarget.value + '(' + event.currentTarget.selectedIndex + ')');
    });
    gridItems = $('#gridContainer > *');
    return console.log(gridItems);
  };

}).call(this);
